/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author mim0x
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Constructor generico PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }
    
    /**
     * Constructor donde recibimos la referencia a la ventana de inicio
     * - Parent hace referencia a la ventana principal que está en ejecución y permite utilizar sus metodos y clases
     * @param parent 
     */
    // Nuevo constructor donde recibimos la referencia al frame principal
    public PanelInicio(VentanaPrincipal parent) {
        initComponents();
        
        // Añadimos el listener del botón aquí para asegurar que se liga a la instancia que se muestra
        btnReserva.addActionListener(e -> {
            System.out.println("Botón Ir a pantalla reserva"); // prueba
            parent.cambiarPantalla("Reservar");
        });
        
        btnContacto.addActionListener(e -> {
            System.out.println("Botón Ir contacto"); // prueba
            parent.cambiarPantalla("Contacto");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoTitulo = new javax.swing.JLabel();
        btnReserva = new javax.swing.JButton();
        btnContacto = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setVerifyInputWhenFocusTarget(false);

        textoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTitulo.setText("Reserva de espacios y salones BK");
        textoTitulo.setToolTipText("Reserve su salón para eventos");
        textoTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReserva.setText("Reserva el salón \"Habana\"");
        btnReserva.setToolTipText("Haga click para reservar este salón");
        btnReserva.setAlignmentY(1.0F);
        btnReserva.setAutoscrolls(true);
        btnReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });

        btnContacto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnContacto.setText("Contacta con nosotros");
        btnContacto.setToolTipText("Información de contacto");
        btnContacto.setAlignmentY(1.0F);
        btnContacto.setAutoscrolls(true);
        btnContacto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnContacto)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed

    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactoActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnContactoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContacto;
    private javax.swing.JButton btnReserva;
    private javax.swing.JLabel textoTitulo;
    // End of variables declaration//GEN-END:variables
}
