/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author mim0x
 */
public class PanelPantallaReserva extends javax.swing.JPanel {

    /**
     * Constructor generico
     */
    public PanelPantallaReserva() {
        initComponents();
    }
    
    /**
     * Constructor donde recibimos la referencia a la ventana de inicio
     * - Parent hace referencia a la ventana principal que está en ejecución y permite utilizar sus metodos y clases
     * @param parent 
     */
    // Nuevo constructor donde recibimos la referencia al frame principal
    public PanelPantallaReserva(VentanaPrincipal parent) {
        initComponents();
        
        // Añadimos el listener del botón aquí para asegurar que se liga a la instancia que se muestra
        btnVolverInicio.addActionListener(e -> {
            System.out.println("Botón Ir a pantalla de inicio"); // prueba
            parent.cambiarPantalla("Inicio");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolverInicio = new javax.swing.JButton();

        btnVolverInicio.setText("Volver al inicio");
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolverInicio)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolverInicio)
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
    }//GEN-LAST:event_btnVolverInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverInicio;
    // End of variables declaration//GEN-END:variables
}
