package GUI;

import java.awt.*;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import javax.imageio.*;

/**
 * Clase que permite crear el "marco" donde aparecerán las diferentes pantallas
 * del programa.
 * <p>
 * Se utiliza cardLayout para hacer la transición</p>
 *
 * @author Cristina García Quintero
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private static JPanel panelContenedor;
    private static CardLayout cardLayout;

    /**
     * Constructor que inicializa el marco principal de la aplicación
     * <p>
     * También inicia el cardLayout que nos sirve para cambiar entre JPanels</p>
     * JPanels
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana

        //Establece el icono del Jframe
        String pathImage = "/LogoBK.png";
        this.setIconImage(new ImageIcon(pathImage).getImage());

        try {
            this.setIconImage(ImageIO.read(this.getClass().getResource("/LogoBK.png")));
        } catch (Exception e) {
        }

        // Crear los paneles
        panelContenedor = new JPanel();
        cardLayout = new CardLayout();

        panelContenedor.setLayout(cardLayout); // Establecemos la estructura de la ventana principal como un cardlayout

        // Añadimos las "Pantallas" o paneles
        panelContenedor.add(new PanelInicio(this), "Inicio");
        panelContenedor.add(new PanelPantallaReserva(this), "Reservar");
        panelContenedor.add(new PanelContacto(this), "Contacto");

        // Añadimos el contenedor al Jframe
        this.setContentPane(panelContenedor);

        // Mostrar la primera pantalla
        cardLayout.show(panelContenedor, "Inicio");
    }

    /**
     * método para cambiar de ventana
     *
     * @param nombrePantalla nombre de la pantalla a la que se quiere cambiar
     */
    public void cambiarPantalla(String nombrePantalla) {
        cardLayout.show(panelContenedor, nombrePantalla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BK Reservas");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(680, 550));
        setName("Frame Principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(680, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
